name: Update Base64 Subscription

on:
  schedule:
    - cron: '0 */5 * * *'  # هر ۵ ساعت اجرا می‌شود
  workflow_dispatch:

jobs:
  update-base64:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Reset base64 folder
        run: |
          rm -rf base64
          mkdir -p base64
          echo "✅ پوشه base64 ریست شد."
          # ریست گزارش
          rm -f report.txt

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run base.py
        run: python base.py

      - name: Show report
        run: |
          cat report.txt
