name: Auto Run Base64 Builder

on:
  schedule:
    - cron: '*/15 * * * *'   # هر 15 دقیقه اجرا می‌شود
  workflow_dispatch:          # اجرای دستی هم داشته باشد

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install requests

      - name: Run base.txt
        run: |
          python base.txt

      - name: Commit all output files
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add base64.txt base64_*.txt *.txt
          git commit -m "auto: update all base64 outputs" || echo "No changes"
          git push
